name: "unit tests"

on:
  push:
  pull_request:

jobs:
  build:
    name: build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: GCC
            os: ubuntu-latest
            cc: gcc
            cxx: g++
          - name: Clang
            os: ubuntu-latest
            cc: clang
            cxx: clang++
          - name: MSVC
            os: windows-latest
            cc: cl
            cxx: cl
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: cmake -S . -B build -DUNIT_TEST=ON

    - name: build
      run: cmake --build build --config Debug

    - name: test
      run: ctest --test-dir build --output-on-failure -C Debug
